name: Python

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Check code formatting
      run: black --check .

  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo-dev libgtk-4-dev cmake gobject-introspection libgirepository-2.0-dev libadwaita-1-dev gir1.2-girepository-2.0
        python -m pip install --upgrade pip
        pip install .
        pip install mypy types-beautifulsoup4 types-requests
    - name: Check code types
      run: mypy -p language_practice

  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo-dev libgtk-4-dev cmake gobject-introspection libgirepository-2.0-dev libadwaita-1-dev
        python -m pip install --upgrade pip
        pip install .
        pip install pylint
    - name: Analyze the code with pylint
      run: pylint language-practice language_practice
